apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: apigateway
    name: apigateway
  spec:
    type: LoadBalancer
    loadBalancerIP: 20.91.197.135
    ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30000
    - name: "https"
      port: 443
      targetPort: 443
      nodePort: 30001
    selector:
      io.kompose.service: apigateway

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: apigateway
    name: apigateway
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: apigateway
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
  
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: apigateway
      spec:
        containers:
        - image: leenpeen/apigateway:latest
          imagePullPolicy: Always
          name: apigateway
          ports:
          - containerPort: 80
          - containerPort: 443
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: ""
          resources: 
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                cpu: 250m
                memory: 2560Mi
          stdin: true
          tty: true
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}

kind: List
metadata: {}