apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: aukio
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: apigateway
    name: apigateway
  spec:
    loadBalancerIP: 20.91.197.135
    type: LoadBalancer
    ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30000
    - name: "https"
      port: 443
      targetPort: 443
      nodePort: 30001
    selector:
      io.kompose.service: apigateway
      app: apigateway

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: authdb
    name: authdb
  spec:
    ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "1433"
      port: 1433
      targetPort: 1433
    selector:
      io.kompose.service: authdb
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: authenticationservice
    name: authenticationservice
  spec:
    ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
    selector:
      io.kompose.service: authenticationservice
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: rabbit
    name: rabbit
  spec:
    ports:
    - name: "15672"
      port: 15672
      targetPort: 15672
    - name: "5672"
      port: 5672
      targetPort: 5672
    selector:
      io.kompose.service: rabbit
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: userdb
    name: userdb
  spec:
    ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "1443"
      port: 1433
      targetPort: 1433
    selector:
      io.kompose.service: userdb
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: userservice
    name: userservice
  spec:
    ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
    selector:
      io.kompose.service: userservice
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: consul
    name: consul
  spec:
    type: LoadBalancer
    ports:
    - name: "8500"
      port: 8500
      targetPort: 8500
    selector:
      io.kompose.service: consul

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: apigateway
    name: apigateway
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: apigateway
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
  
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: apigateway
      spec:
        containers:
        - image: leenpeen/apigateway:latest
          imagePullPolicy: Always
          name: apigateway
          ports:
          - containerPort: 80
          - containerPort: 443
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: ""
          resources: {}
          stdin: true
          tty: true
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: authdb
    name: authdb
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: authdb
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
  
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: authdb
      spec:
        containers:
        - env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: Your_password123
          image: mcr.microsoft.com/mssql/server
          imagePullPolicy: Always
          name: authdb
          ports:
          - containerPort: 5672
          - containerPort: 1433
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: authenticationservice
    name: authenticationservice
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: authenticationservice
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
  
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: authenticationservice
      spec:
        containers:
        - image: leenpeen/authenticationservice:latest
          imagePullPolicy: Always
          name: authenticationservice
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
          stdin: true
          tty: true
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: rabbit
    name: rabbit
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: rabbit
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
  
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: rabbit
      spec:
        containers:
        - image: rabbitmq:3-management
          imagePullPolicy: Always
          name: rabbitmq
          ports:
          - containerPort: 15672
          - containerPort: 5672
          resources: {}
        hostname: rabbit
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: userdb
    name: userdb
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: userdb
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: userdb
      spec:
        containers:
        - env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: Your_password123
          image: mcr.microsoft.com/mssql/server
          imagePullPolicy: Always
          name: userdb
          ports:
          - containerPort: 5672
          - containerPort: 1433
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: userservice
    name: userservice
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: userservice
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
  
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: userservice
      spec:
        containers:
        - image: leenpeen/userservice:latest
          imagePullPolicy: Always
          name: userservice
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
          stdin: true
          tty: true
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: consul
    name: consul
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: consul
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: consul
      spec:
        containers:
        - args:
          - consul
          - agent
          - -dev
          - -log-level=warn
          - -ui
          - -client=0.0.0.0
          image: consul:latest
          imagePullPolicy: Always
          name: consul
          ports:
          - containerPort: 8500
          resources: {}
        hostname: consul
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}

kind: List
metadata: {}