apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: authdb
    name: authdb
  spec:
    ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "1433"
      port: 1433
      targetPort: 1433
    selector:
      io.kompose.service: authdb
  status:
    loadBalancer: {}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: authdb
    name: authdb
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: authdb
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
  
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: authdb
      spec:
        containers:
        - env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: Your_password123
          image: mcr.microsoft.com/mssql/server
          imagePullPolicy: IfNotPresent
          name: authdb
          ports:
          - containerPort: 5672
          - containerPort: 1433
          resources: 
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                cpu: 250m
                memory: 2560Mi
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
kind: List
metadata: {}