version: '3.4'

services:

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: RabbitMQ
    ports:
        - "15672:15672"
        - "5672:5672"
    expose:
        - 15672
        - 5672

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - "8500:8500"

  aukiodb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: AukioDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5676:5672"
        - "1463:1433"

  apigateway:
    image: leenpeen/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
        - "20001:80"
        - "20002:443"

  userservice:
    image: leenpeen/userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
        - "20020:80"
        - "20021:443"

  authenticationservice:
    image: leenpeen/authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    ports:
        - "20010:80"
        - "20011:443"

