version: '3.4'

services:

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: RabbitMQ
    ports:
        - "15672:15672"
        - "5672:5672"
    expose:
        - 15672
        - 5672

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - "8500:8500"

  userdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: UserDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5674:5672"
        - "1443:1433"

  authdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: AuthDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5675:5672"
        - "1453:1433"

  apigateway:
    image: leenpeen/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
        - "50002:80"
        - "50003:443"

  userservice:
    image: leenpeen/userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
        - "50020:80"
        - "50021:443"

  authenticationservice:
    image: leenpeen/authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    ports:
        - "50022:80"
        - "50023:443"

