apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: userservice
    name: userservice
  spec:
    ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
    selector:
      io.kompose.service: userservice
  status:
    loadBalancer: {}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: userservice
    name: userservice
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: userservice
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o aukiodepl.yml
  
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: userservice
      spec:
        containers:
        - image: leenpeen/userservice:latest
          imagePullPolicy: Always
          name: userservice
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: 
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                cpu: 250m
                memory: 2560Mi
          stdin: true
          tty: true
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}

kind: List
metadata: {}