name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore Aukio.sln
    - name: Build
      run: dotnet build Aukio.sln --no-restore
      
  securitytest:
    runs-on: ubuntu-latest
    steps:
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
       target: https://aukiofrontend.azurewebsites.net/
      

